"""add jar reference

Revision ID: 09fc95828825
Revises: 1a96dde6a102
Create Date: 2026-08-10 18:47:19.003043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fc95828825'
down_revision: Union[str, Sequence[str], None] = '1a96dde6a102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('jar_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_transactions_jar_id'), 'transactions', ['jar_id'], unique=False)
    op.drop_constraint(op.f('transactions_account_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'mono_jars', ['jar_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'mono_accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_account_id_fkey'), 'transactions', 'mono_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_transactions_jar_id'), table_name='transactions')
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'jar_id')
    # ### end Alembic commands ###
