"""add mono client id to users

Revision ID: 1a96dde6a102
Revises: 6445bd0dc67d
Create Date: 2026-08-09 10:18:24.133024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a96dde6a102'
down_revision: Union[str, Sequence[str], None] = '6445bd0dc67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mono_client_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_mono_client_id'), 'users', ['mono_client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mono_client_id'), table_name='users')
    op.drop_column('users', 'mono_client_id')
    # ### end Alembic commands ###
