"""add mono tables

Revision ID: 6445bd0dc67d
Revises: 
Create Date: 2026-06-08 20:19:12.761630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6445bd0dc67d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('mono_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('mono_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mono_account_id', sa.String(), nullable=False),
    sa.Column('send_id', sa.String(), nullable=True),
    sa.Column('currency_code', sa.Integer(), nullable=False),
    sa.Column('cashback_type', sa.String(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('credit_limit', sa.BigInteger(), nullable=False),
    sa.Column('masked_pan', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mono_accounts_mono_account_id'), 'mono_accounts', ['mono_account_id'], unique=True)
    op.create_index(op.f('ix_mono_accounts_user_id'), 'mono_accounts', ['user_id'], unique=False)
    op.create_table('mono_jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mono_jar_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('goal', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency_code', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mono_jars_mono_jar_id'), 'mono_jars', ['mono_jar_id'], unique=True)
    op.create_index(op.f('ix_mono_jars_user_id'), 'mono_jars', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('mono_transaction_id', sa.String(), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('original_mcc', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('operation_amount', sa.BigInteger(), nullable=True),
    sa.Column('currency_code', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.BigInteger(), nullable=True),
    sa.Column('cashback_amount', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('receipt_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('counter_edrpou', sa.String(), nullable=True),
    sa.Column('counter_iban', sa.String(), nullable=True),
    sa.Column('counter_name', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mono_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_mono_transaction_id'), 'transactions', ['mono_transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_time'), 'transactions', ['time'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_time'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_mono_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_mono_jars_user_id'), table_name='mono_jars')
    op.drop_index(op.f('ix_mono_jars_mono_jar_id'), table_name='mono_jars')
    op.drop_table('mono_jars')
    op.drop_index(op.f('ix_mono_accounts_user_id'), table_name='mono_accounts')
    op.drop_index(op.f('ix_mono_accounts_mono_account_id'), table_name='mono_accounts')
    op.drop_table('mono_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
