"""add categorization models

Revision ID: b0ca73639879
Revises: 09fc95828825
Create Date: 2026-09-03 16:56:19.594765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ca73639879'
down_revision: Union[str, Sequence[str], None] = '09fc95828825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('merchant_category_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_key', 'mcc', name='uq_user_merchant_mcc')
    )
    op.create_index(op.f('ix_merchant_category_mappings_category_id'), 'merchant_category_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_merchant_category_mappings_user_id'), 'merchant_category_mappings', ['user_id'], unique=False)
    op.create_table('transaction_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('merchant_mapping_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_mapping_id'], ['merchant_category_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_categories_category_id'), 'transaction_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_categories_merchant_mapping_id'), 'transaction_categories', ['merchant_mapping_id'], unique=False)
    op.create_index(op.f('ix_transaction_categories_transaction_id'), 'transaction_categories', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_categories_transaction_id'), table_name='transaction_categories')
    op.drop_index(op.f('ix_transaction_categories_merchant_mapping_id'), table_name='transaction_categories')
    op.drop_index(op.f('ix_transaction_categories_category_id'), table_name='transaction_categories')
    op.drop_table('transaction_categories')
    op.drop_index(op.f('ix_merchant_category_mappings_user_id'), table_name='merchant_category_mappings')
    op.drop_index(op.f('ix_merchant_category_mappings_category_id'), table_name='merchant_category_mappings')
    op.drop_table('merchant_category_mappings')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
