// Generated by the design repo (tools/export-tab-icons.js), don't edit by hand.

export const TAB_ICONS = {
  light: {
    index: { default: require('../../assets/tab-icons/light/index-idle.png'), selected: require('../../assets/tab-icons/light/index-active.png') },
    budgets: { default: require('../../assets/tab-icons/light/budgets-idle.png'), selected: require('../../assets/tab-icons/light/budgets-active.png') },
    add: { default: require('../../assets/tab-icons/light/add-idle.png'), selected: require('../../assets/tab-icons/light/add-active.png') },
    analytics: { default: require('../../assets/tab-icons/light/analytics-idle.png'), selected: require('../../assets/tab-icons/light/analytics-active.png') },
    assistant: { default: require('../../assets/tab-icons/light/assistant-idle.png'), selected: require('../../assets/tab-icons/light/assistant-active.png') },
  },
  dark: {
    index: { default: require('../../assets/tab-icons/dark/index-idle.png'), selected: require('../../assets/tab-icons/dark/index-active.png') },
    budgets: { default: require('../../assets/tab-icons/dark/budgets-idle.png'), selected: require('../../assets/tab-icons/dark/budgets-active.png') },
    add: { default: require('../../assets/tab-icons/dark/add-idle.png'), selected: require('../../assets/tab-icons/dark/add-active.png') },
    analytics: { default: require('../../assets/tab-icons/dark/analytics-idle.png'), selected: require('../../assets/tab-icons/dark/analytics-active.png') },
    assistant: { default: require('../../assets/tab-icons/dark/assistant-idle.png'), selected: require('../../assets/tab-icons/dark/assistant-active.png') },
  },
};

export type TabIconName = keyof typeof TAB_ICONS.light;
